### ISSUE TITLE
spin up a chat channel of some sort

### ISSUE THREAD

**Issue by shiftkey** [scientistproject/Scientist.net#120]

**Comment by JoshHiles** [comment]
I think its between MS Teams or Slack?
Both have a free plan and have the ability to have plugins to things which is nice.
@shiftkey is it worth setting up a team on here as well, just for the ease of group mentions!

**Comment by M-Zuber** [comment]
Something interesting I have seen done (don't remember who right now) was to have a slack team for the maintainers, but to use [Spectrum](https://spectrum.chat/) or Gitter for the community

**Comment by JoshHiles** [comment]
So i've set up [Gitter for the community](https://gitter.im/scientistproject/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link) tried adding a badge but i cant push to repo!
In the process of creating a team chat, it may just be on gitter!?
