### ISSUE TITLE
Rewrite for .NET 6

### ISSUE THREAD

**Issue by JoshHiles** [scientistproject/Scientist.net#135]
My thoughts are that we use github actions to deploy a 2.x.x-alpha to NuGet which we can use for testing etc. with the wider community.

In regards to the main branch, we keep that going and alive for the time being with the outlook to have a 1.x.x branch where the old code sits for any bug fixes and such. However i think people should moving on from old .net versions!

**Comment by marblekirby** [comment]
what are the thoughts on 
- new repo for the .net 6 rewrite
- GitHub action to deploy new 2.x.x to nuget.org
- maintaining the 1.x.x code or leave it as is to focus on the .net 6 rewrite 

What are the current permissions on this repository, who currently owns and manages likes of PRs?

**Comment by JoshHiles** [comment]
So

- I think having a new branch is more or less the same as having a new repo, might be less confusing to people & they will be able to see our progress and any updates for the old stuff in one place rather than mutiple
- So yeh, we can use i do believe GitHub actions to hopefully publish a 2.x.x-alpha release to nuget.org with clear warnings that is in alpha until we are ready
  - added bonus of using github actions is we can do automated dependency updates where necessary and static code analysis
- I think the 1.x.x code has been around that long with minimal maintance that i think we should continue to have a 1.x.x branch where we can support it for a while but give everyone enough notice to move up to higher .NET 6 maybe??
- Current permissions are
  - @shiftkey is an admin
  - Scientist.NET Maintainers (Admin privileges)
    - @rogertinsley 
    - @shawnwildermuth 
    - @paulbreen 
    - @M-Zuber 
    - @JoshHiles 

At the moment the master branch (at somepoint we should change to main) is protected
- 2 people must review the code
- It will dismiss stale pull request approvals when new commits are pushed 
- It requires status checks to pass before merging 
- Branch be up to date before merging
- Require conversation resolution before merging 
- Require signed commits
- Require linear history
- Only the Scientist.NET Maintainers can push to master branch
- All these setting include the admins

**Comment by M-Zuber** [comment]
I've on the tail end of a long burn out, but I do hope to get back into things.

My two cents is the best way to rejuvenate the project would be a new branch in the existing repo and not a new repo as it would hamper discovery

**Comment by marblekirby** [comment]
Great summary. I'd very much like to be apart of this rewrite.

Creating a new branch would be alot less confusing since we already have the 1.x and 2.x branches here.

**Comment by JoshHiles** [comment]
@marblekirby Awesome stuff!

Ahh i see we have 2.x tag & a 2.x release hidden away!

3.x it is then!

**Comment by marblekirby** [comment]
Great shall we create the new branch and get some issues created for the 2.x.x release?

**Comment by JoshHiles** [comment]
3.x (pretend theres a winky face because i couldnt find it)

Shall we go with feature/core-rewrite for the time being and at somepoint down the line merge that into a 3.x branch or?

**Comment by marblekirby** [comment]
Shall we get an issue created for the 3.x 😉 and discuss there.

I think that the feature/core-rewrite is fine, or some reference to .net 6 might be helpful as Microsoft have dropped "core" for the .net 5/6 releases.

**Comment by JoshHiles** [comment]
Closing to move over to https://github.com/scientistproject/Scientist.net/issues/136
