### ISSUE TITLE
Actions for code scanning

### ISSUE THREAD

**Issue by JoshHiles** [scientistproject/Scientist.net#138]
## Description

**As a** maintainer,
**I want** code scanning to be ran on a PR
**So that** automatically detect common vulnerability and coding errors

## Acceptance Criteria

- When a PR is open a action runs
  - CodeQL Analysis
- The PR status for the code scanning
  -  When fails is red & wont allow the PR to be merged
  -  When success is green and will allow the PR to be merged

**Comment by M-Zuber** [comment]
What are the current top options here?
can we use [dependabot](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates) for this?

**Comment by marblekirby** [comment]
i can start looking at this issue next

**Comment by JoshHiles** [comment]
Sorry @marblekirby only just seen your comment!

**Comment by marblekirby** [comment]
That is ok, I didn't round to adding codeql in quick enough anyway, will assign @josh-hiles
